### ISSUE TITLE
Performing right click on element using WatiN for IE

### ISSUE THREAD

**Issue by iwx1** [featurist/coypu#105]
How to perform right click or trigger contextmenu on any element in IE using WatiN?
I have seen that it can be done using Selenium WebDriver but the same it not possible with WatiN.
I am working on IE11.
Thanks for your help!
If this is not available with Coypu could you please implement? If available could you please share with me an example code?
Thanks!

**Comment by obstar** [comment]
watiN is dead, coypu doesn't support it anymore
