### ISSUE TITLE
ExecuteJavaScript with parameters

### ISSUE THREAD

**Issue by drauch** [featurist/coypu#128]
Currently ExecuteScript is always called with new object[0] as second argument (see SeleniumWebDriver.ExecuteScript), however, sometimes you want to pass an argument to the ExecuteScript() call. Currently I have to use 

    (browser.Native as IJavaScriptExecutor).ExecuteScript("myscript", scope.Native as IWebElement)

which is not all too nice :-)

Would be nice if there is parameter support.

**Comment by adiel** [comment]
Any chance you could do a PR for this one, looks straight forward to pass the params list all the way down?

**Comment by drauch** [comment]
Done that, see https://github.com/featurist/coypu/pull/130 (review points for you @ pull request comments).

**Comment by drauch** [comment]
Guess we can close this, after #130 has been merged :-)
