### ISSUE TITLE
How to support others wrappers above WebDriver

### ISSUE THREAD

**Issue by caspernick** [featurist/coypu#132]
We can specify type of Driver in BrowserSession. Coypu uses this type to create a new instance of WebDriver, and invoke default constructor of this type.

I cannot integrate 'Protractor' with Coypu because 'NgWebDriver' doesn't have default constructor.
It will be very good if Coypu framework will have possibility to take existing WebDriver instance. Or just support NgWebDriver also.

**Comment by adiel** [comment]
You can just instantiate your NgWebDriver however you like and pass it to the constructor of Coypu.BrowserSession - this overrides the Type set in ConfigurationSettings.

See: https://github.com/featurist/coypu#using-a-custom-selenium-webdriver-profile

Going to close, but do re-open if I've misunderstood. Thanks.
