### ISSUE TITLE
Freezing - VS2013 Windows 8.1 x64

### ISSUE THREAD

**Issue by Paulo-Faustino** [featurist/coypu#133]
Hi there. I wanted to try Coypu but I can't get it to work, it freezes the form and no exceptions are thrown.

Sample code:

var sessionConfiguration = new SessionConfiguration
            {
                Driver = typeof(SeleniumWebDriver),
                Browser = Coypu.Drivers.Browser.Chrome
            };

            using (var browser = new BrowserSession())
            {
                //App freezes forever
            }

**Comment by adiel** [comment]
Not had any other reports of this. Could you try just starting webdriver by itself and seeing what happens, e.g.

```
IWebDriver  driver = new ChromeDriver();
driver.Navigate().GoToUrl("https://www.google.com");
```

Does that work for you?

**Comment by Paulo-Faustino** [comment]
Hi Adiel.
Thanks so much, your code works fine and I just figured that the following code bellow will work as well.
I have a question in regards to taking screenshots which I'm getting blank on he code bellow as well.

var browser = new BrowserSession(new SessionConfiguration()
            {
                Driver = typeof(SeleniumWebDriver),
                Browser = Coypu.Drivers.Browser.Chrome
            });

            browser.Visit("http://www.google.com");
            browser.FillIn("lst-ib").With("hakuna matata " + DateTime.Now.ToString());
            browser.ClickButton("btnG");
            browser.SaveScreenshot(Guid.NewGuid().ToString() + ".png", System.Drawing.Imaging.ImageFormat.Png);
            browser.Dispose();
