### ISSUE TITLE
NUnit 3 Support

### ISSUE THREAD

**Issue by Blundell89** [featurist/coypu#142]
Hey,

We've recently upgraded our test framework to NUnit v3.2 and needed to make some changes to support the breaking changes in the framework.

I've opened a PR on our fork (https://github.com/LiberisLabs/coypu/pull/1/files) but would be happy to open a PR to your repo if you were interested in merging the changes? If there's anything you think should be changed too I'm happy to receive comments.

We have added the `Ignore` attribute to some tests that we couldn't get to run (8 of them) and have followed the previous convention of moving the NUnit v2.6.3 integration to its own project. We have also upgraded the NUnit version in tests where possible but some are restricted due to the target framework of the projects.

Thanks

Lee

**Comment by adiel** [comment]
Sure think, make a PR. What you've done looks like the right approach to me. Might take me a little while to review it, but thanks!

**Comment by Jetski5822** [comment]
done

**Comment by miketonguk** [comment]
Any ideas when the Nuget package will be updated to contain the new Nunit3 support?
