### ISSUE TITLE
Waitbeforeclick not waiting

### ISSUE THREAD

**Issue by graceawalker** [featurist/coypu#146]
browser.ClickButton("Search", new Options { WaitBeforeClick = TimeSpan.FromMilliseconds(0.2) } )

This doesn't seem to work for me - I've increased it to 20 seconds but it is definitely not pausing before clicking, I've looked in the source code and I can't see anything crazy in there that means it shouldn't wait?

**Comment by obstar** [comment]
fixed in https://github.com/featurist/coypu/pull/191

**Comment by obstar** [comment]
Coypu 3.0.0-rc has been released https://github.com/featurist/coypu/releases/tag/3.0.0-rc
