### ISSUE TITLE
Add a build agent

### ISSUE THREAD

**Issue by blundell89** [featurist/coypu#149]
Coypu should use a build agent to ensure that the solution builds and all tests run successfully.

**Comment by Blundell89** [comment]
@adiel It'd be good to get this on Travis before I pick up the work for v3 - would you be able to either sign up for Travis and add the repo or make me an admin? Thanks

**Comment by obstar** [comment]
Adrian created account for coypu: https://travis-ci.org/featurist/coypu
to do before next release
