### ISSUE TITLE
ChromeDriver Options

### ISSUE THREAD

**Issue by oyjonass** [featurist/coypu#150]
Hi

In chrome 52.0.2743.116 i need to pass no-sandbox as options to ChromeDriver.

But in DriverFactory you do this

 if (browser == Browser.Chrome)
                return new ChromeDriver();

Seems like there is no option to do this?

https://bugs.chromium.org/p/chromium/issues/detail?id=615396
Go to comment 70

**Comment by obstar** [comment]
Hey oyjonass,
Look for CustomProfile in
https://github.com/featurist/coypu/blob/master/src/Coypu.AcceptanceTests/ApiExamples.cs

this should allow you to create instance of chrome with desired options

**Comment by oyjonass** [comment]
Hi obstar
Nice. Thank you. Can confirm that this worked for me.

        public class CustomChromeProfileSeleniumWebDriver : SeleniumWebDriver
        {
            public CustomChromeProfileSeleniumWebDriver(Browser browser)
                : base(CustomProfile(), browser)
            {
            }

            private static RemoteWebDriver CustomProfile()
            {
                ChromeOptions chromeOptions = new ChromeOptions();
                chromeOptions.AddArguments("test-type");
                chromeOptions.AddArguments("start-maximized");
                chromeOptions.AddArguments("--disable-extensions");
                chromeOptions.AddArguments("no-sandbox");

                return new ChromeDriver(chromeOptions);
            }
        }



        [SetUp]
        public void SetUp()
        {
            var configuration = new SessionConfiguration
            {
                Timeout = TimeSpan.FromMilliseconds(2000),
                Driver = typeof(CustomChromeProfileSeleniumWebDriver),
                Browser = Browser.Chrome,
            };
            browser = new BrowserSession(configuration);
        }
