### ISSUE TITLE
getAttribute

### ISSUE THREAD

**Issue by ErikV88** [featurist/coypu#152]
How can I get a attribut of a element ? 

Then I try  
Dim vUrl As String = browser.FindCss(".file > a", Options.FirstExact)("href")

I got this error :
OpenQA.Selenium.WebDriverException : Unexpected error . System.Net.WebException : Unable to connect to the remote server ---> System.Net.Sockets.SocketException : Can not connect because the target machine actively refused 127.0.0.1:10291

**Comment by adiel** [comment]
Not sure of the syntax for VB.net (is that?) but regardless your stack trace implies you have a problem with webdriver itself, does it even open a browser?

**Comment by ErikV88** [comment]
In c# it is : string vUrl = browser.FindCss(".file > a", Options.FirstExact)("href");
It run the test to i step to this line :)

**Comment by obstar** [comment]
correct way to get attribute you want (its also described in coypu documentation):
`string vUrl = browser.FindCss(".file > a", Options.FirstExact)["href"];`
