### ISSUE TITLE
How to upload a file using native dialog box

### ISSUE THREAD

**Issue by codyreo** [featurist/coypu#155]
Hi there,

Not sure if this is an issue or possibly there is a solution I haven't figured out. The scenario is a user clicks a button on a website that opens up a native windows dialog box for file upload. How do i interact with that dialog box using coypu?

When using just selenium I think you can just send the file path and click enter using sendKeys(). However when trying to do the same with coypu the sendKeys method also needs an element as a parameter. In this scenario what would the element be?

Is this an unsupported feature or is there a way to do it I haven't figured out yet?

Many Thanks!
Orla

**Comment by obstar** [comment]
there is one example in the tests (https://github.com/featurist/coypu/blob/master/src/Coypu.Drivers.Tests/When_uploading_files.cs):
`var directoryInfo = new DirectoryInfo(Path.GetTempPath());`
           `     var fullPath = Path.Combine(directoryInfo.FullName, someLocalFile);`
               ` using (File.Create(fullPath))`
             `   {`
              `  }`
               ` var textField = Field("forLabeledFileFieldId");`
               ` Driver.Set(textField, fullPath);`
