### ISSUE TITLE
Selenium 3.X Support

### ISSUE THREAD

**Issue by ztoliver** [featurist/coypu#156]
Will there be an update to Selenium 3.X? As we get pushed to Chrome 54+ it will become impossible to use Coypu as the next version of the chromedriver will probably by Chrome 53+.

**Comment by obstar** [comment]
+1

**Comment by adiel** [comment]
Just needs someone to fork it, upgrade Selenium, run the tests and fix any API breaking changes. 

I won't be able to look at this till I get back from holiday week commencing 8th Nov, but if someone wants to do the above please go ahead.  cc @Blundell89

**Comment by GameOSX** [comment]
@adiel - anything moved with this?

**Comment by obstar** [comment]
yeah I've upgraded on my fork to selenium 3.0.1 also but still got 19 tests in solution which are failing - I work on fixing those first

**Comment by ztoliver** [comment]
@adiel Thanks. Can we get a beta build on NuGet?

**Comment by chaswiso** [comment]
TY @obstar and @adiel

**Comment by imorpher** [comment]
Cheers all! Any idea on when we might get the updated NuGet?

**Comment by ztoliver** [comment]
+1 on updated Nuget, we may have to stop using Coypu soon if we can't use Selenium 3.

**Comment by chaswiso** [comment]
We've come to rely heavily on Coypu too, but I'm concerned as well. 
Adrian, I'd be happy to give some feedback on a beta version if you upload to nuget. 

--Chris

**Comment by adiel** [comment]
Apologies again to all. I have had no windows for a while and have passed the keys to two other contributors to take forward.

I will chase today and make sure a new version comes to nuget asap.

**Comment by Jetski5822** [comment]
Hey Guys, sorry for the delay on this, I have picked it up.

I will look to roll out an update over the next day or so.... on top of that I have started on a dotnet core branch, though this is totally experimental at the moment.

**Comment by ztoliver** [comment]
@Jetski5822 Looking forward to it! Thanks guys!

**Comment by chaswiso** [comment]
Thanks guys! 
Really appreciate everyones' help on this

--Chris

**Comment by Jetski5822** [comment]
I have 12 tests failing, I'll push to a branch if people are curious.

N

**Comment by Jetski5822** [comment]
Pre-release https://www.nuget.org/packages/Coypu/2.12.0-beta1

**Comment by ztoliver** [comment]
@Jetski5822 Thanks! I tried installing the pre-release but it doesn't seem to add the Coypu reference. Anyone else have this issue?

**Comment by Jetski5822** [comment]
@ztoliver I screwed up the nuget package.... fixed! just tried it! - go for beta2

**Comment by ztoliver** [comment]
Just ran our entire test suite of 321 functional tests using Coypu 2.12 - beta2, Selenium 3.0.1, and ChromeDriver 2.27. Ran without issue.

**Comment by chaswiso** [comment]
Woohoo!
I ran with geckodriver this morning. Will retest tomorrow and share some results. 

--Chris

**Comment by Jetski5822** [comment]
@chaswiso  I updated the Gecko Driver from 11 to 13 btw.

**Comment by chaswiso** [comment]
Thanks
I'll make sure I'm using 13

--Chris

**Comment by ztoliver** [comment]
Selenium 3.1.0 was released about 5 days ago. Think we can get a beta-3 with this version? Seems they fixed some bugs.

**Comment by Jetski5822** [comment]
@ztoliver I have upgraded locally already, however there is one test that is erroring that I want to fix before releasing. Will try to take a look this weekend. sorry for the delay.

**Comment by Jetski5822** [comment]
@ztoliver just pushed to nuget.... beta-3

**Comment by Jetski5822** [comment]
Closing as there are two betas out

**Comment by ztoliver** [comment]
@Jetski5822 Thanks a ton. Are we ready for a stable version now? We are not allowed to use beta versions in our organization, but I've been running locally fine since the second beta.
