### ISSUE TITLE
ConsiderInvisibleElements doesn't not seem to work in all cases

### ISSUE THREAD

**Issue by Grepsy** [featurist/coypu#162]
I keep getting the "Cannot inspect the text of invisible elements." exception even though I've set the `ConsiderInvisibleElements = true` configuration option. I noticed the following code:

```
if (textPattern != null && options.ConsiderInvisibleElements)
                throw new NotSupportedException("Cannot inspect the text of invisible elements.");
```
at https://github.com/featurist/coypu/blob/master/src/Coypu/Drivers/Selenium/SeleniumWebDriver.cs#L91

This seems incorrect to me. Shouldn't the `options.ConsiderInvisibleElements` be negated?

**Comment by Grepsy** [comment]
Or maybe I'm just misunderstanding this whole thing and inspecting text of invisible elements is not supported at all, regardless of the `ConsiderInvisibleElements` option. But that seems silly :-)

**Comment by Jetski5822** [comment]
@adiel whats your thoughts?

**Comment by adiel** [comment]
My memory is that Selenium was returning empty string in this case maybe,
which was a nasty failure, so this exception was to make it explicit that
you can't do this. Was a while ago though...
