### ISSUE TITLE
Coypu 2.12.0-beta2 weird behavior, changing focused element before finishing filling the field.

### ISSUE THREAD

**Issue by tiger4589** [featurist/coypu#164]
I have downloaded the new Coypu beta package and trying to use it in my automation tests.
I used to use FireFox before but now changed to Chrome, and I downloaded the latest ChromeDriver.exe. 
While the automation are running, I noticed that first of all, WaitBeforeClick option isn't always working, or not at all, plus another weird issue when filling in the text field in a web page sometimes it's not waiting until the whole intended text is filled in and directly change the focus to another field and continue the test and obviously finish failing.

**Comment by ztoliver** [comment]
Are you using GeckoDriver 13? It was updated from 11 to 13 in this build.

**Comment by tiger4589** [comment]
I was using Google Chrome when I found this issue, and I was using the latest ChromeDriver.

**Comment by Jetski5822** [comment]
@tiger4589 that is weird, can you update to the latest? Beta3? and tell me if you are still seeing the same issues?

**Comment by tiger4589** [comment]
@Jetski5822 I am sorry I can't do that anymore, we decided to revert back to the latest stable version so we don't lose time in development. If I was able to do it in the near future I will make sure to test it.

**Comment by obstar** [comment]
https://github.com/featurist/coypu/pull/191 fix will be available with next release

**Comment by obstar** [comment]
Coypu 3.0.0-rc has been released https://github.com/featurist/coypu/releases/tag/3.0.0-rc
