### ISSUE TITLE
2.12 Beta

### ISSUE THREAD

**Issue by jhorne12345** [featurist/coypu#165]
Hello - 

I just got the latest beta off of Nuget. What features are new? I can't find any documentation on the newest features. Thx.

**Comment by obstar** [comment]
update to selenium 3.0.1

**Comment by Jetski5822** [comment]
I havent added any new features per say to Coypu, just upgraded Selenium.

I guess:
+ Added new MS Edge Driver
+ Fixed https://github.com/featurist/coypu/pull/158
