### ISSUE TITLE
Wierd Section Finder

### ISSUE THREAD

**Issue by DanielIndie95** [featurist/coypu#168]
`public string Section(string locator, Options options)
        {
            return
                Descendent() +
                Where(
                    TagNamedOneOf(sectionTags) +
                    And(
                        Child() +
                        Where(TagNamedOneOf(headerTags) + and + IsText(locator, options)) +
                        or + HasId(locator)));
        }`
is the current code
why isnt it :
` public string Section(string locator, Options options)
        {
            return
                Descendent() +
                Where(
                    TagNamedOneOf(sectionTags) +
                    and +
                        IsTextShallow(locator, options) +
                        or + HasId(locator));
        }`
in my case it found the exact elements which got the text or id ( the other didnt)
and i didnt quite understand why the headers are neccessery

**Comment by obstar** [comment]
@DanielIndie95 what is the HTML code against which you run it?

**Comment by obstar** [comment]
no response
