### ISSUE TITLE
Focus on an element (moveToElement)

### ISSUE THREAD

**Issue by bulldetektor** [featurist/coypu#169]
Hi,

What's the recommended way to focus an element, e.g. making sure the element is within the visible area, using Couypu? 

I know there's an 'moveToElement' action on the Selenium WebDriver, but I guess that won't work if we're using the Chrome driver? 

Should we execute javascript with the [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)?

**Comment by Jetski5822** [comment]
Hey, moveToElement should work with the chrome driver, I just tested it. There is a bug in the Gecko driver which I have worked around.

**Comment by obstar** [comment]
@bulldetektor there is method in coypu Hover() which will hover over element and make it visible
