### ISSUE TITLE
Calling .Now() on ElementScope inside iframe leads to failed .Exists() check on elements outside iframe

### ISSUE THREAD

**Issue by FlorianDecker** [featurist/coypu#172]
Hi,

we found a relatively weird interaction in our tests when dealing with iframe. Whenever .Now() is called on an Element inside of an iframe, successive .Exists() checks on Elements outside the iframe are returning false (altough they are made on the outside ElementScope). The same thing happens in the other direction (calling .Now() on Element outside of iframe --> .Exists() check failing on elements inside iframe)

Example:

    var sessionConfiguration = new SessionConfiguration();
    sessionConfiguration.Browser = Browser.Chrome;
    sessionConfiguration.Timeout = TimeSpan.FromSeconds(3);

    var browserSession = new BrowserSession(sessionConfiguration);
    browserSession.Visit("http://localhost:8000");

    var rootScope = browserSession.FindCss("html");
    var outsideFrame = rootScope.FindId("OutsideFrame");

    Assert.That(outsideFrame.Exists(), Is.True);

    var frame = browserSession.FindFrame("frame");
    var frameRootElement = frame.FindCss("html");

    frameRootElement.Now();

    Assert.That(rootScope.FindId("OutsideFrame").Exists(), Is.False); //Should be True
    Assert.That(frameRootElement.FindId("InsideFrame").Exists(), Is.True);

    outsideFrame.Now();

    Assert.That(rootScope.FindId("OutsideFrame").Exists(), Is.True);
    Assert.That(frameRootElement.FindId("InsideFrame").Exists(), Is.False); //Should be True

Files:
index.html

    <!DOCTYPE html>

    <html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <body>
        <h1 id="OutsideFrame">OutsideFrame</h1>
        <iframe name="frame" src="frame.html">
        </iframe>

    </body>
    </html>

frame.html

    <!DOCTYPE html>

    <html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <title></title>
    </head>
    <body>
        <h1 id="InsideFrame">InsideFrame</h1>
    </body>
    </html>

I would guess it has something to do with the SeleniumDriver switching between the frame and original window. But .Now() does not seem to be affected from the same behaviour. If i implement my own Exists function with .Now(), everything works as expected

    try
    {
      scope.ElementFinder.Options.Timeout = TimeSpan.Zero;

      var exists = scope.Exists (Options.NoWait);

      if (!exists)
      {
        try
        {
           scope.Now();
        }
        catch (Exception)
        {
          // Sometimes the first scope.Now() call fails although the element exist. So we swallow that first exception and just try again.
        }

        scope.Now();
      }

      return true;
        
    }
    catch (MissingHtmlException)
    {
      return false;
    }
    catch (MissingWindowException)
    {
      return false;
    }
    catch (StaleElementException)
    {
      return false;
    }
    catch (StaleElementReferenceException)
    {
      return false;
    }
    finally
    {
      scope.ElementFinder.Options.Timeout = scopeTimeoutBackup;
    }

Is this a bug with .Exists()? Has the .Now() approach any drawbacks?

**Comment by lanfear** [comment]
fwiw, pretty sure i'm seeing something related to this.  while the steps above are certainly more explicit repro steps, in my setup I have a test effectively doing:

(note: Browser = ScenarioContext.Current.Get<BrowserSession>( "browser" ) )

`Browser.RetryUntilTimeout( () => Assert.IsTrue( Browser.FindFrame( "embed-media" ).FindCss( ".video-view" ).Exists(), $"Expected to iframe" ) );`

followed by

`browser.FindCss( ".t-close-video" ).Click();`

where '.t-close-video' is a button in the parent/root frame.  

This test had worked as is for quite a long time, I am currently upgrading to seleinum 3.4.0 + Coypu 2.12.0-beta3 and test started failing.

If I comment out the check for `Browser.FindFrame( "embed-media" ).FindCss( ".video-view" )` everything passes.  So, seemingly the call to FindFrame is changing the context of the DOM?

**Comment by Jetski5822** [comment]
Does this fail on the latest release? Not the beta versions~?

**Comment by FlorianDecker** [comment]
We encountered the problem with 2.9.1.
I just tested it with 2,14.0. Sadly the problem still exists in this version.
