### ISSUE TITLE
Coypu.NUnit has constraint on NUnit < 3.0

### ISSUE THREAD

**Issue by cob999** [featurist/coypu#173]
The matchers in the Coypu.NUnit package are used in the examples on the main page, but this package is quite out of date and can't be used with latest NUnit packages. Are there plans to update it or is it replaced with something else?

```
Install-Package Coypu.NUnit
Install-Package : Unable to resolve dependencies. 'NUnit 3.7.1' is not compatible with 'Coypu.NUnit 1.1.0 constraint: NUnit (>= 2.6.3 && < 3.0.0)'.
```

**Comment by Jetski5822** [comment]
Not any more :)
