### ISSUE TITLE
Issue automating google ClickButton not working in runtime

### ISSUE THREAD

**Issue by JakeTrans** [featurist/coypu#178]
Hello,

We are looking to replace some of our currently WATin Test with coypu and are just getting used to the new style however we seem to be running into issues automating the screen (just doing a Google search as a general test)

This is our code so far -

 var sessionConfiguration = new SessionConfiguration
            {
                AppHost = @"google.com",
                Port = 5555,
                SSL = false,
                Timeout = TimeSpan.FromSeconds(1),
                RetryInterval = TimeSpan.FromSeconds(0.1)
                

            };

            sessionConfiguration.Driver = typeof(Coypu.Drivers.Watin.WatiNDriver);
            sessionConfiguration.Browser = Coypu.Drivers.Browser.InternetExplorer;

            using (var browser = new BrowserSession(sessionConfiguration))
            {
                browser.Visit(@"http://www.google.com");
                browser.FillIn("q").With("watin");
                browser.ClickButton("btnK");
            }

The Fillin seems to work every time (however is there anything like SetAttributeValue in WATin) however the click only seems to work if you breakpoint the code and go to it, I assume we are missing something but are unsure

P.S we are using the Nuget package.

Thanks you for your help.

**Comment by obstar** [comment]
@JakeTrans 
ad 1. 
in this example with google, the page code has two input elements with attribute 'name=btnK' so to solve issues with clicking button you can pass Options arg:
`browser.ClickButton("btnK", Options.First);`
ad 2.
there is no direct SetAttributeValue() method in coypu but you could try to execute javascript code which will do that for you e.g.
`browser.ExecuteScript("document.getElementsByName('q')[0].value='watin'");`

**Comment by JakeTrans** [comment]
Thank you for the help, this seem to be working now.
