### ISSUE TITLE
Cannot find options wrapped in optgroup

### ISSUE THREAD

**Issue by brennfoster** [featurist/coypu#185]
Coypu cannot find option elements that are wrapped in optgroup like:
```    
<select>
    <optgroup label="Some Label">
        <option>First option</option>
        <option>Second option</option>
    </optgroup>
</select>
```

**Comment by obstar** [comment]
@brennfoster as workaround you can search for option group and then select option from it

```
var optionGroup = _browser.FindId("Female");
optionGroup.SelectOption("Jessica");
```

as working directly from Select() is a bit more tricky to do, I was thinking about something like that:
```
_browser.Select("Jessica").InGroup("Female").From("peopleList")
```
but I need more time to think about it, unless someone got already a solution for that..
