### ISSUE TITLE
How to wait until one of the two elements is present

### ISSUE THREAD

**Issue by MarkKharitonov** [featurist/coypu#187]
I posted the question here - https://stackoverflow.com/questions/50917590/coypu-wait-until-one-of-the-two-elements-is-present

How can I wait until either a certain css appears or a certain text?

Right now my solution is this:

```
    browser.Visit(uriContext.Uri.ToString());
    var deadline = DateTime.UtcNow.Add(WebAppWarmUpTimeout);
    while (DateTime.UtcNow < deadline)
    {
    	if (browser.HasContent("404 - File or directory not found.", SmallTimeoutOptions))
    	{
    		Assert.Fail("404");
    	}
    	else if (browser.FindCss("body nav a", "Job Search", SmallTimeoutOptions).Exists())
    	{
    		break;
    	}
    }
```

Is there a better way to do it?

**Comment by adiel** [comment]
Yes there is:

https://github.com/featurist/coypu#finding-states-nondeterministic-testing

Appreciate if you answered your own question on SO with this too. Thanks!

**Comment by MarkKharitonov** [comment]
Done. Thank you very much.
