### ISSUE TITLE
'Typing' speed of BrowserSession.Fillin.With massively variable

### ISSUE THREAD

**Issue by bwmodular** [featurist/coypu#188]
I'm finding that the speed at which Coypu fills in text boxes can vary massively from one field to another in the same test.
So I have a test which fills in a few fields, then moves on to another section and fills in a few more.
The first fields, it's almost as if the fields are filled in one go - ie the whole word appears almost instantaneously, wheras for other fields, it's as if it's being typed letter by letter so that the whole field can take a few seconds to to fill in.
Any ideas what might be causing this, or what I can do.

I have other projects where none of the tests exhibit this behaviour, wheras all of the tests in this project do, with the same version of Coypu, ChromeDriver, etc,

I've attached a zip file which has a recording showing that the first two fields are filled in almost instantaneously wheras the next fields are much slower.

Using Coypu 2.14
Selenium.WebDriver.ChromeDriver 2.40.0

[IRAMS.zip](https://github.com/featurist/coypu/files/2227842/IRAMS.zip)

**Comment by obstar** [comment]
@bwmodular are those other projects and tests performed against the same form as presented on that video? 
Maybe there is some weird implementation of those inputs fields on that specific page because if it works fine everywhere else..
