### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by eparizzi** [featurist/coypu#190]
Last commit is from a year ago. 

Please, if you're not going to maintain your OS libraries, please archive the repo or write a notice in the README. It takes 2 minutes.

Thanks

**Comment by pawepaw** [comment]
Well, since you didn't get any answer yet it seems that it's dead.

**Comment by obstar** [comment]
I got on my fork updated version to selenium 3.14, plus removed old stuff like support for WatiN. I can do PR to this repo I guess

**Comment by adiel** [comment]
That would be an awesome way to maintain this project :)

I personally (one of the original authors) am not working on .Net for a few
years. But https://github.com/Jetski5822 has admin rights and will look at
your PR.

If any of you want to be even more involved than just contributing PRs you
would be very welcome!

I wouldn't say it is dead, because lots of people are using it still every
day. But it's had much in the way of contributions for a while for sure.

Thanks
Adrian

**Comment by pawepaw** [comment]
Well ok there is no development in this project but people are still using it and reporting issues but it doesn't mean that it's maintained.

**Comment by adiel** [comment]
I agree, it's not being maintained well. What it needs is someone(s) using
it regularly to be doing this. There are a lot of people using it, so I
would hope this can happen.

I think we should transfer the repo to it's own organisation to start with
coypu/coypu and then really try to encourage some new maintainers to get on
board.

wdyt?

**Comment by obstar** [comment]
in my company we use it for 2yr now and we keep it up to date plus we created recently extension to coypu 
 to support page object - I need to add some tests around that and merge it to coypu solution, and after that next step is to migrate it to .net standard 2.0

**Comment by brigs** [comment]
@adiel sounds like a good idea. My organization might be able to contribute.

**Comment by aalsamoht** [comment]
Long time lurker first time poster. This sounds like a good idea @adiel

**Comment by obstar** [comment]
@Hawxy I just get admin rights for this repo and to nuget from @adiel I will very soon (probably during the weekend) release new version of Coypu with support for selenium v3.14.

@eparizzi I will be also actively developing and maintaining this project from now on.

**Comment by Hawxy** [comment]
Great to hear!
