### ISSUE TITLE
coypu - release of new version 3.0.0-rc

### ISSUE THREAD

**Issue by obstar** [featurist/coypu#192]
I'm thinking about releasing a new version of coypu which supports selenium v3.14.

My initial idea was to release it coypu with new version of .net framework (net471) but as it was pointed out by @LukeOwlclaw and @Hawxy (in https://github.com/featurist/coypu/pull/191#discussion_r239801936) there is out there quite a few legacy projects using lower versions of .net framework. 
Having that in mind I've checked that last release of coypu v2.14 use net3.5.  
From what I see the master branch with current net4.7.1 can be easily downgraded to .net4.0 without breaking anything, if I go to net3.5 there is conflict with one dependency which was updated to newer version and it expects .net4.0 so..

Current plan is to bump it .net framework from net3.5 to net4.0 - the lowest possible version that is required by one of updated dependency. 
Because it is breaking change I will follow sem-ver and I will bump major version of coypu and because it happen to be same major version as selenium webdriver I will sync to it:
coypu.3.14.0

Is there are more concerns regarding .net framework version?

**Comment by Hawxy** [comment]
Following on from our conversation, I'm likely going to do a PR that dual-targets netstandard2.0 and net45, so the library will be compatible with the common set of netfx versions alongside .net core.

I think net40 is a bit too old and might end up holding development back at some point. The majority of users are likely on at least net45.

**Comment by obstar** [comment]
yeap, the .net45 sounds great.

**Comment by obstar** [comment]
@Hawxy got question about that dual-target of netstandard2.0 and net45
When I'm looking on this: https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md
is clearly that netstandard2.0 supports only:
> .NET Core 2.0
> .NET Framework 4.6.1

same goes for that source https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support that for net45 is netstandard1.1

unless current dual target mean that:
1. all projects that got net45 and above can use it coypu
2. all projects from netstandard2.0 and above can use it coypu (including support for .NET Core 2.0 and above)
?
Just want to double check that before releasing.

**Comment by Hawxy** [comment]
So, dual-targeting this way effectively says "Hey, this package works under anything that supports net45 and above **OR** implements NS2.0", thus nuget will permit an install on any project that meets that requirement and resolve the appropriate dependencies.

Specifically, we're targeting NET45 + NS2.0 because Selenium.WebDriver targets NET35/NET40/NET45/NS2.0 and we have to keep our targets in-line with our dependencies.

So yes, this package will work on any .NET Framework 4.5+ or .NET Core 2.0+ project.

**Comment by obstar** [comment]
@Hawxy perfect. I will do release later today or at the end of the week.
