### ISSUE TITLE
NuSpec issues

### ISSUE THREAD

**Issue by Hawxy** [featurist/coypu#199]
Thanks for the v3.0.0-rc release, but there's a problem

I'm not why you added a nuspec when the csproj's were already updated with nuget information (which generate nuget packages whenever `dotnet pack` or a publish is run). nuspecs are considered outdated compared to csproj definitions and really shouldn't be used anymore outside of complex use-cases.

NETStandard.Library is also not a required dependency and can be removed

**Comment by obstar** [comment]
ok, I will switch to that when releasing proper ''latest release' of 3.0.1

**Comment by obstar** [comment]
@Hawxy the only issue I've got with csproj instead of nuspec is this one:
- [Allow an upper limit Version for ProjectReference references in nupkg from `dotnet pack` to support semver](https://github.com/NuGet/Home/issues/5556)

so the nuget package for Coypu.NUnit that came from csproj is:
```  
<group targetFramework=".NETFramework4.5">
        <dependency id="Coypu" version="3.0.1" exclude="Build,Analyzers" />
        <dependency id="NUnit" version="[3.11.0, 4.0.0)" exclude="Build,Analyzers" />
      </group>
 <group targetFramework=".NETStandard2.0">
        <dependency id="Coypu" version="3.0.1" exclude="Build,Analyzers" />
        <dependency id="NUnit" version="[3.11.0, 4.0.0)" exclude="Build,Analyzers" />
 </group>
```
from nuspec
```
 <group targetFramework=".NETFramework4.5">
        <dependency id="Coypu" version="[3.0.1, 4.0.0)" />
        <dependency id="NUnit" version="[3.11.0, 4.0.0)" />
</group>
<group targetFramework=".NETStandard2.0">
        <dependency id="Coypu" version="[3.0.1, 4.0.0)" />
        <dependency id="NUnit" version="[3.11.0, 4.0.0)" />
 </group>
```

I guess I can manually modify that..

**Comment by obstar** [comment]
@Hawxy new release https://github.com/featurist/coypu/releases/tag/3.0.1
ok compromise is that coypu is created from csproj and coypu.nunit from nuspec when they fix the issue with version range for project references I will be able to switch fully to csproj for coypu.nunit
