### ISSUE TITLE
Clear Browser Cache

### ISSUE THREAD

**Issue by christianbumann** [featurist/coypu#202]
It would be nice to have the possibility to clear the browser cache or it is possible to do this with send keys (e.g. Ctrl + F5) to the browser window?

**Comment by obstar** [comment]
@christianbumann webdriver API doesn't have possibility to clear cache in browser, sending keys to browser window will have to be done on system level so selenium will not help with that.
If you wanna reuse browser window the closest solution is to using `_browserSession.Driver.Cookies.DeleteAll()` but thats just cookies.
The best way is to have fresh webdriver instance for each test that way you will have browser instance without cache, cookies or history from previous tests.

**Comment by christianbumann** [comment]
Thx
