### ISSUE TITLE
saving file as png saves the contents as jpg

### ISSUE THREAD

**Issue by basimc4** [featurist/coypu#203]
in coypu v3

when calling SaveScreenshot with filename sample.png, the contents of the file are actual jpg ie the mime type is image/jpg instead of image/png

**Comment by basimc4** [comment]
this method doesn't strip out the leading dot in the file extension. the format will always be Jpeg

>         internal static ScreenshotImageFormat GetImageFormat(string fileName)
        {
            var extension = new FileInfo(fileName).Extension.ToLower()
                                                  .Replace("jpg", "jpeg");

            ScreenshotImageFormat format;
            if (AreEqual(extension, ScreenshotImageFormat.Bmp))
                format = ScreenshotImageFormat.Bmp;
            else if (AreEqual(extension, ScreenshotImageFormat.Gif))
                format = ScreenshotImageFormat.Gif;
            else if (AreEqual(extension, ScreenshotImageFormat.Jpeg))
                format = ScreenshotImageFormat.Jpeg;
            else if (AreEqual(extension, ScreenshotImageFormat.Png))
                format = ScreenshotImageFormat.Png;
            else if (AreEqual(extension, ScreenshotImageFormat.Bmp))
                format = ScreenshotImageFormat.Bmp;
            else
                format = ScreenshotImageFormat.Jpeg;

            return format;
        }

**Comment by basimc4** [comment]
Hi @joshski @adiel , 
I have a fix for this issue as well as a test case for it.  How do i go about submitting it.
Thanks
B

**Comment by basimc4** [comment]
i figured it out . see pull request #204

**Comment by obstar** [comment]
@basimc4 thanks, I will take a look on you PR

**Comment by boydpatterson** [comment]
I just wanted to add that WebDriver on .NET Core only supports PNG image format.  Since PNG files are being unintentionally saved as JPEG image format, that causes WebDriverException every time.  Workaround is to bypass BrowserSession and use native WebDriver ITakesScreenshot functionality.

**Comment by obstar** [comment]
@basimc4 
sorry, I can't reproduce it your issue, I've added a test for PNG and when debugging - the code in ImageFormatParser.cs works correctly

**Comment by berckoi** [comment]
@obstar can this issue please be reopened? I also just ran into it too.

I'm using Coypu in a .NET Core test suite which only supports PNG files. I have my file extension listed as .png, but am getting the following error:

> .NET Core does not support image manipulation, so only Portable Network Graphics (PNG) format is supported

This is just like @basimc4  described.

```
var filename = "filename.png";
var extension = new FileInfo(fileName).Extension; //This will return .png
```

Coypu's ImageFormatParse.AreEqual() function is:
```
private static bool AreEqual(string extension, ScreenshotImageFormat imageFormat) 
{
    return extension.Equals(imageFormat.ToString(),        //This will be ".png"
            StringComparison.InvariantCultureIgnoreCase);  //This will be "png"
}
```

**Comment by obstar** [comment]
@berckoi ok, I will go back to it with proper .net core project

**Comment by berckoi** [comment]
Thanks for the quick turn around @obstar! I updated to Coypu 3.1.1 and can confirm that my screenshots are generating flawlessly!

**Comment by obstar** [comment]
@berckoi np
