### ISSUE TITLE
Firefox fails to switch out of iframe

### ISSUE THREAD

**Issue by iam-mholle** [featurist/coypu#205]
We have discovered that when switching into an iframe using Firefox, the scope gets set to the iframe scope and does not switch back (like it does in e.g. Chrome) when trying to select elements in the outer scope. They can't be found.

Some digging revealed that Firefox Marionette does not switch back to the `DefaultContent` when switching out of an iframe using `SwitchTo().Window(...)`. This issue is known to Mozilla and a bug report can be found [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1305822). Since it appears like it will not be fixed by Mozilla in the near future, have you considered adding a fix to your library?

It would seem that the issue could be fixed by changing `SeleniumWindowManager.SwitchToWindow(...)` to the following:

```csharp
public void SwitchToWindow(string windowName)
{
    if (LastKnownWindowHandle != windowName || SwitchedToAFrame)
    {
        _webDriver.SwitchTo()
                  .Window(windowName);

        // Fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1305822 
        if (_webDriver is FirefoxDriver)
        {
            _webDriver.SwitchTo()
                      .DefaultContent();
        }

        LastKnownWindowHandle = windowName;
    }

    _switchedToFrame = null;
    _switchedToFrameElement = null;
}
```

This would make sure that the context resets to the `DefaultContent` like it should do, according to the [W3C WebDriver specification](https://www.w3.org/TR/webdriver/#switch-to-window), and does not have any side effects.

**Comment by obstar** [comment]
I will take a look, thanks.

**Comment by iam-mholle** [comment]
This also affects `FrameFinder.FrameContentsMatch(...)`, and could be fixed the same way:

```csharp
private bool FrameContentsMatch(IWebElement e,
                                string locator,
                                Options options)
{
    var currentHandle = _selenium.CurrentWindowHandle;
    try
    {
        var frame = _seleniumWindowManager.SwitchToFrame(e);
        return
            frame.Title == locator ||
            frame.FindElements(By.XPath($".//h1[{_xPath.IsText(locator, options)}]"))
                 .Any();
    }
    finally
    {
        _selenium.SwitchTo()
                 .Window(currentHandle);

        // Fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1305822 
        if (_selenium is FirefoxDriver)
        {
            _selenium.SwitchTo()
                     .DefaultContent();
        }
    }
}
```

**Comment by iam-mholle** [comment]
Hi @obstar,
just wondering if there are any updates on this issue?
