### ISSUE TITLE
chromedriver 75 - coypu failing to start a driver

### ISSUE THREAD

**Issue by obstar** [featurist/coypu#206]
with new version of chromdedriver v75 coypu fail to start browser, multiple acceptance test are failing

**Comment by Hawxy** [comment]
Funnily enough, I got hit with the #205 issue today and cracked open Coypu again to do an update pass. All tests happily pass on ChromeDriver 75 for me with no startup issues.

**Comment by obstar** [comment]
thanks for info, that simplifies release of new coypu version. Probably early next week.
