### ISSUE TITLE
`Options.SingleExact` identical to `Options.SingleSubstring`

### ISSUE THREAD

**Issue by cyungmann** [featurist/coypu#213]
From 
https://github.com/featurist/coypu/blob/5a3c3ffe5976b54911955500977c96b4472121e3/src/Coypu/Options.cs#L94

```csharp
public static Options SingleExact = Merge(Single, Substring);
public static Options SingleSubstring = Merge(Single, Substring);
```

...`SingleExact` should instead be defined as `Merge(Single, Exact)`

**Comment by obstar** [comment]
thx @cyungmann  fixed in commit 5059a74b7a0022241599f5af341e5cc9dc04f036
