### ISSUE TITLE
Firefox (still) fails to switch out of iframe

### ISSUE THREAD

**Issue by iam-mholle** [featurist/coypu#214]
Follows #205, #207 

Unfortunately, the problem described in #205 still persists.

#207 changed `SeleniumWindowManager.SwitchToWindow(string windowName)` to the following:
```csharp
public void SwitchToWindow(string windowName)
{
    // Fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1305822 
    var isFirefox = _webDriver is FirefoxDriver;

    if (LastKnownWindowHandle != windowName || !isFirefox && SwitchedToAFrame)
    {
        _webDriver.SwitchTo().Window(windowName);
        LastKnownWindowHandle = windowName;
    }

    if (isFirefox && SwitchedToAFrame)
    {
        _webDriver.SwitchTo().DefaultContent();
    }

    _switchedToFrame = null;
    _switchedToFrameElement = null;
}
```

I did not find out why `SwitchedToAFrame` is not always `true` when being inside an `iframe`, but the webdriver specification states the following:

> Switching window will select the current top-level browsing context used as the target for all subsequent commands. In a tabbed browser, this will typically make the tab containing the browsing context the selected tab.

The related Firefox issue is still open: https://bugzilla.mozilla.org/show_bug.cgi?id=1305822

My interpretation of the specification is that you should always switch back to the default content regardless, please consider this workaround for Firefox:

```csharp
public void SwitchToWindow(string windowName)
{
    if (LastKnownWindowHandle != windowName || SwitchedToAFrame)
    {
        _webDriver.SwitchTo()
                  .Window(windowName);

        // Fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1305822 
        if (_webDriver is FirefoxDriver)
        {
            _webDriver.SwitchTo()
                      .DefaultContent();
        }

        LastKnownWindowHandle = windowName;
    }

    _switchedToFrame = null;
    _switchedToFrameElement = null;
}
```

**Comment by obstar** [comment]
@iam-mholle thanks, I'm implemting your fix in 498f40cf68e416df8cd9ff176d2a1d830470738b
