### ISSUE TITLE
Slenium Grid & Sauce Labs with Coypu

### ISSUE THREAD

**Issue by Kavitha-Vijay** [featurist/coypu#216]
Hi All ,
I am trying to set up Grid for parallel execution. I need similar driver in Coypu as same as  Remoteweb driver in selenium . Please support . Did any one tried and implemented ?

Thanks .

**Comment by Kavitha-Vijay** [comment]
I have used CustomDriver as follows for SauceLabs:
using System;
using Coypu;
using Coypu.Drivers;
using Coypu.NUnit.Matchers;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Coypu.Drivers.Selenium;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium;
using System.Threading;
using OpenQA.Selenium.Support.UI;

namespace Coypu_Test
{
    [TestClass]
    public class UnitTest4
    {
        [TestMethod]
        public void Test1()
        {
            var configuration = new SessionConfiguration { Driver = typeof(SauceLabsDriver) };
            SauceLabsDriver Driver = new SauceLabsDriver(configuration.Browser);
            BrowserSession browser = new BrowserSession(configuration, Driver);
            browser.MaximiseWindow();
            browser.Visit("http://executeautomation.com/demosite/Login.html");
            // Thread.Sleep(30000);

            browser.FillIn("userName").With("admin");
            browser.FillIn("password").With("password");
            //Click login Button
            browser.ClickButton("Login");

            //Select title
            browser.Select("Ms.").From("TitleId");

            //Type Initial, FirstName, MiddleName
            browser.FillIn("Initial").With("I");
            browser.FillIn("FirstName").With("FirstName");
            browser.FillIn("MiddleName").With("MiddleName");

            //Select Gender RadioButton
            browser.Choose("female");
            //Check Languge Radiobutton
            browser.Check("Hindi");
            browser.Uncheck("english");
            //Save button
            browser.ClickButton("Save");
            // Query to check whether the page contains text
            NUnit.Framework.Assert.IsTrue(browser.HasContent("Execute Automation Selenium Test Site"));
            //Assert statement to check whether text is present in the page
            NUnit.Framework.Assert.That(browser, Shows.Content("Execute Automation Selenium Test Site"));
            //Assert statement to check whether value is present in particular fiels
            NUnit.Framework.Assert.That(browser.FindField("Initial"), Shows.Value("I"));
            //Kill driver
            browser.Dispose();
        }
        public class SauceLabsDriver : SeleniumWebDriver
        {
            //public SauceLabsDriver(Browser browser) : base(new RemoteWebDriver(new Uri(@"http://192.168.43.209:4444/wd/hub"),
            //      new DesiredCapabilities("chrome", "79.0.3945.130", Platform.CurrentPlatform)), browser)
            //{
            //}
            public SauceLabsDriver(Browser browser) : base(new RemoteWebDriver(new Uri(@"https://Kavitha_24:99b3ff2a-db17-49a6-81ef-ae22c563b222@ondemand.us-west-1.saucelabs.com:443/wd/hub"),
      new DesiredCapabilities("chrome", "79", Platform.CurrentPlatform)), browser)
            {
            }
        }

    }

}
___________________

1. In SauceLabs the browser is getting Launched , Maximized , Navigated to URL
But failed to interact with elements .

Let me know Am I missing Any

**Comment by obstar** [comment]
@Kavitha-Vijay you've got example here https://github.com/featurist/coypu#sauce-labs
