### ISSUE TITLE
Review implementation of Dispose-methods

### ISSUE THREAD

**Issue by N-Olbert** [featurist/coypu#219]
Currently the dispose method of the class **BrowserSession** (others porbably aswell) cannot be overridden, which makes it more tricky than it should be to add custom disposal behaviour for inheriting classes. It is also against the suggested 
[Dispose-Pattern](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#dispose-and-disposebool).

Suggestion: Implement the common Dispose-Pattern and move the current disposal logic to a new method with the signature
`protected virtual void Dispose(bool disposing)`

**Comment by obstar** [comment]
@N-Olbert 18afb371f16de1e9dc3553ad41d9963b38af276e that will do or I'm missing something here?

**Comment by N-Olbert** [comment]
@obstar Yes, that's it 👍 
Thanks in advance.
