### ISSUE TITLE
Selenium 4 and .NET 6

### ISSUE THREAD

**Issue by sbowler** [featurist/coypu#222]
I'm trying to find out if there are plans to eventually support Selenium 4 and/or .NET 6?

**Comment by obstar** [comment]
yes they are

**Comment by sbowler** [comment]
There appears to be a pull to do this, https://github.com/featurist/coypu/pull/225 . Not sure why it's been sitting so long with no response though. You were pretty quick to respond to this. Ideally this would also support .NET Core.

**Comment by ben-soler** [comment]
Does this project plan to keep itself updated with the latest updates of Selenium and .Net Core?
