### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by sbowler** [featurist/coypu#227]
Nothing has really happened here in over a year. A lot of people are wanting Selenium 4 support and other updates. I wonder if there is anyone willing to maybe fork this and maintain it if no one is going to maintain this? Unless someone with access is willing to give another person permissions to maintain this repo.

**Comment by adiel** [comment]
Yes! (see https://github.com/featurist/coypu/pull/225#issuecomment-1486868849)

Would you like to volunteer @sbowler? Anyone else?

**Comment by adiel** [comment]
I actually came back through here as been working with [Playwright ](https://playwright.dev) from Node and it occurred to me that:

* It is sorely missing the capybara/coypu treatment
* Selenium is basically dead

A playwright driver should be super easy really. It's just implementing this interface  - https://github.com/featurist/coypu/blob/master/src/Coypu/Drivers/Selenium/SeleniumWebDriver.cs. The driver test suite should make that pretty easy iirc.

**Comment by sbowler** [comment]
At this point I'm likely to fork this and merge the pulls that have been sitting for several months now. I probably won't have a lot of time for work, but I can at least merge pulls and do a minimal amount of work to maintain this library as long as people are willing to support it.

**Comment by sbowler** [comment]
@obstar If you are not going to maintain this repo, will you give me or someone else access to merge pulls and create releases?

**Comment by obstar** [comment]
@sbowler done, invitation send
