### ISSUE TITLE
Not an issue per se

### ISSUE THREAD

**Issue by jacrys** [featurist/coypu#230]
This isn't an issue; I just wanted to say a huge thank you to @sbowler and @adiel for taking up this mantle again. I hated to see this project I love stagnate and flame out. Your efforts are seen and greatly appreciated!

**Comment by adiel** [comment]
❤️ Full time dad here with a 1 yr old about to start nursery so apologies for the delay, but I'm gonna get onto that Playwright driver soon I swear, hopefully that will give it a few more years of life before flame out!
