### ISSUE TITLE
Playwright setup and experiences

### ISSUE THREAD

**Issue by bjowes** [featurist/coypu#232]
Thanks for adding Playwright support - several projects I have been involved with lately has considered migrating to Playwright due to limitations with Selenium. This provides a possibility to evaluate playwright without a huge rewrite and even to migrate in steps if needed!

Just started testing this out and have managed to get it running. A couple of things I've noted:

# Setup, incorrect docs?
The readme says 
`sessionConfiguration.Driver = typeof (Playwright);`
but I had to use
`sessionConfiguration.Driver = typeof(Coypu.Drivers.Playwright.PlaywrightDriver);`

# Basic authentication
With Selenium webdrivers it was possible to pass the credentials inside the url (like http://user:pass@site.org). It does not seem like Playwright supports this url format. There are proper ways to set HttpCredentials in Playwright, but there is not straightforward way to pass them into Coypu since those parts are private. My current workaround is to perform this before the first Visit call to the site:
```
var context = (Microsoft.Playwright.IBrowserContext) Browser.Driver.Native;
var authenticationString = $"{username}:{password}";
var base64EncodedAuthenticationString = Convert.ToBase64String(System.Text.ASCIIEncoding.ASCII.GetBytes(authenticationString));
context.SetExtraHTTPHeadersAsync(new Dictionary<string, string> { { "Authorization", "Basic " + base64EncodedAuthenticationString } });
```
This works, but is kind of clunky. If you have plans to extent the API to allow passing HttpCredentials (and possibly more options) that would be great, otherwise I would be happy to put together a PR for it.

# ExecuteScript return type
With Selenium webdriver, the return type for calls to ExecuteScript was castable to the expected type (booleans could be cast to bool, numbers to long). Playwright seems to return strings instead. Although this isn't a breaking change for Selenium users, it would be more convenient if the interfaces match. At least it should be documented.

**Comment by adiel** [comment]
Great feedback thanks! Agree with all these suggestions. Even partially implemented PR would be very welcome, otherwise I'll try look at them soon as I can.

**Comment by sbowler** [comment]
I don't think I got a notification for this for some reason or I missed it. Unfortunately I haven't even had a chance to test out the last release yet with my test framework using it. I agree with Adrian, this is excellent feedback and these sound like legit issues and improvement for a PR.

**Comment by adiel** [comment]
> Setup, incorrect docs?

Readme corrected and merged.

**Comment by adiel** [comment]
On the basic auth question, I'm inclined just to parse these from the url in the Playwright driver for consistency rather than introduce a whole new API bearing in mind where we are. @bjowes would that satisfy?

**Comment by bjowes** [comment]
That would be fine @adiel

**Comment by adiel** [comment]
These points are addressed in #235 and #233
Could I get a quick review from one of you two then we can ship these.

**Comment by bjowes** [comment]
Reviewed

**Comment by adiel** [comment]
@sbowler would you mind releasing v 4.2.0? It should be ready to go in master now. Thx

**Comment by sbowler** [comment]
I should be able to do that. Not quite sure when. Unfortunately I've been sick and a bit behind on things now.
