### ISSUE TITLE
ExecuteScript returns "System.Collections.Generic.Dictionary`2[System.String,System.Object]"

### ISSUE THREAD

**Issue by refractalize** [featurist/coypu#35]
Lets imagine you had this code:

```
var result = browser.ExecuteScript("return {one: 1, two: 2};");
Console.WriteLine(result);
```

It would print out:

```
System.Collections.Generic.Dictionary`2[System.String,System.Object]
```

This is because Selenium is returning a Dictionary<string, object>, but Coypu is doing a .ToString() on it. See here in `SeleniumWebDriver`:

```
public string ExecuteScript(string javascript, Scope scope)
{
    if (NoJavascript)
        throw new NotSupportedException("Javascript is not supported by " + browser);

    elementFinder.SeleniumScope(scope);
    var result = JavaScriptExecutor.ExecuteScript(javascript);
    return result == null ? null : result.ToString();
}
```

So, we could return a JSON string of the object, or we could return an `object`, which could be a dictionary, leaving the caller to cast, or we could return a `dynamic` wrapping the JS object. Wasn't sure how to proceed, and didn't want to break the current API.

**Comment by obstar** [comment]
fixed in https://github.com/featurist/coypu/commit/aceeec19df4d5cf437940f369eafeb2fc4efc584, long time ago
