### ISSUE TITLE
NoSuchElementException find element by ID (only InternetExplorer)

### ISSUE THREAD

**Issue by dstoianov** [featurist/coypu#53]
here is example one:

`browser.FindId("ct_myBox_txtSearch").FillInWith("some text");`
has an exception NoSuchElementException

and the same code by API works as expected
`IWebElement search=  driver.FindElement(By.Id("ct_myBox_txtSearch"));`
`search.Clear();`
`search.SendKeys("Cheese");`

reproduced only on IE, (IE9 win7)

**Comment by wtilton** [comment]
Getting the same thing:

	browser.ClickButton("Sign in");

with the HTML

<button class="btn btn-primary center welcomeButton ng-binding" ng-show="welcomeVm.authInfo.isRegistered &amp;&amp; welcomeVm.authInfo.userInSystem &amp;&amp; !welcomeVm.authInfo.isLocked &amp;&amp; !welcomeVm.authInfo.isRejected" ng-click="welcomeVm.login()"><i class="fa fa-sign-in"></i> Sign in as Will (CAC)</button>

I also changed it to: browser.ClickButton("Sign in as Will (CAC)"); with no success.

This is clearly on the page. And both Chrome and FireFox Selenium drivers are working just fine... :(

Versions:
Coypu 2.10.0.0
Coypu.NUnit 1.0.2.0
Coypu.Drivers.Watin 2.3.0.0

**Comment by EtharAlali** [comment]
Was this ever solved? I assume not. This seems to fail completely when running remotely. It can run locally, and I can even log on to the box and run it manually on that box. What it definitely does not do is run within a CI environment and indeed, it also can't capture a screenshot (just a black box). This may or may not be related.
